var commands = [
	{
		command: 'help',
		description: 'Te tiro la lista de cosas que puedo hacer.'
			+ ' Soy medio pedorro todavía, pero más pedorro sos vos que interactuás con un bot sin utilidad.'
			+ '\nPara cosas útiles, hablá con el lukebot, la dankie o el spippatore.',
		getMessage: function() {
			var message = 'Estas son las cositas que puedo hacer\n';
			for (var i = 0; i < commands.length; i++) {
				var command = commands[i];
				message += '\n'
					+ '\/' + command.command
					+ ': ' + command.description;
			}
			return message;
		}
	},
	{
		command: 'callejeros',
		description: 'Te tiro un verso de Callejeros (inocentes, la música no mata)',
		getMessage: function() {
			return verses[Math.floor(Math.random() * verses.length)];
		}
	},
	{
		command: 'fact',
		description: 'Te tiro una posta pedorrísima que copié de una página del orto (y encima la mayoría están escritas para el ojete)',
		getMessage: function() {
			return facts[Math.floor(Math.random() * facts.length)];
		}
	},
	{
		command: 'vaporize',
		description: 'sadboy2001-ize your message',
		getMessage: function(string) {
			var finalString = '';
			var chars = string.split('');
			for (var i = 0; i < chars.length; i++) {
				if (i > 0) {
					finalString += ' ';	
				}
				finalString += chars[i];
			}

			finalString = '__' + finalString + '__';

			return finalString;
		}
	}
];

var verses = [
	'VOCES, SOLO VOCES COMO ECOS',
	'COMO ATROCES CHISTES SIN GRACIA',
	'HACE MUCHO TIEMPO ESCUCHO VOCES, Y NI UNA PALABRA',
	'NO ESCUCHO Y SIGOOOO, PORQUE MUCHO DE LO QUE ESTA PROHIBIDOO ME HACE VIVIIIRR',
	'NO ME PERSIGOOO, PORQUE MUCHO DE LO QUE ESTA PROHIBIDOO ME HACE FELIZ',
	'CALLEJEROS INOCENTES',
	'LA MÚSICA NO MATA',
	'Acá te mandaría algún meme con la cara del de Callejeros y algún fuego, pero para eso está el otro bot.'
];

var facts = [
	'El filósofo griego Platón pensaba que el amor era una enfermedad mental grave',
	'Ernes Vincent Wright escribio una nobela llamada "Gadsby" que contiene mas de 50,000 palabras, y ninguna de ellas contienen la letra "e".',
	'Todas las termitas del mundo juntas pesan 10 veces mas que todos los humanos juntos.',
	'En el siglo 19 en Inglaterra, el intento de suicidio era castigado con la horca.',
	'Se estima que millones de arboles en el mundo son plantados accidentalmente por ardillas que entierran sus nueces y se olvidan donde las escondieron.',
	'Oler platanos y/o manzanas verdes pueden ayudar a bajar de peso.',
	'En el espacio los astronautas no pueden llorar porque a falta de atracción gravitatoria, las lagrimas no pueden fluir.',
	'El nombre más común en el mundo es Mohammed.',
	'El numero romano para 1666 es MDCLXVI. Este año es famoso por ser la unica vez en la historia en la cual la fecha ha sido escrita con todos los numeros romanos desde el valor mas alto hasta el valor mas bajo (1000+500+100+50+10+5+1)',
	'Thomas Alba Edison, el inventor de la bombilla electrica, tenia miedo a la obscuridad.',
	'El primer año de un perro equivale a 21 años humanos, cada año canino posterior es de 4 años humanos.',
	'111,111,111 x 111,111,111= 12,345,678,987,654,321',
	'Un bulto de oro puro del tamaño de una cajita de cerillos puede ser aplanado hasta hacer una hoja del tamaño de una cancha de tenis.',
	'Despues de abrir la tumba del Rey Tutankhamen, su pene desapareció, aún no se sabe si se les extravió o fue robado.',
	'La silla eléctrica fue inventada por un dentista.',
	'En Bulgaria, los bulgaros mueven la cabeza de arriba a abajo para decir \'no\' y de un lado a otro para decir \'si\'.',
	'Un hombre llamado Charles Osborne tuvo hipo durante 69 años.',
	'Los camellos tienen tres párpados para protejerse de las tormentas de arena.',
	'El unico continente sin reptiles o serpientes es la Antartica.',
	'Los perros y los gatos tambien son diestros o zurdos, como los humanos.',
	'La cucaracha tiene dos cerebros, uno en la cabeza y otro menor en su cola.',
	'Asi como las huellas digitales, la impresion de la lengua es diferente en cada persona.',
	'Una especie de rana venenosa tiene suficiente veneno como para matar alrededor de 2,200 personas.',
	'Se rumora que chupar una moneda de cobra puede causar que el analizador de aliento alcoholico marque cero',
	'Se imprime mas dinero del juego de Monopolio en un año que lo que se imprime de dinero real en todo el mundo.',
	'En Bangladesh, los niños de 15 años pueden ser encarcelados por hacer trampa en sus examenes finales.',
	'La mayoria de las particulas de polvo en las casas estan hechas de piel muerta.',
	'El ojo del avestruz es mas grande que su cerebro.',
	'Tweety (Piolin) el canario de las caricaturas de Warner Brothers solia ser un pajaro bebe sin plumas, hasta que lo censuraron e hicieron que le pusieran plumas porque se veia desnudo.',
	'El Martes es el día más productivo de la semana.',
	'Elvis Presley tenía el cabello rubio y se lo pintaba negro',
	'Las manzanas son mas eficientes que la cafeina para mantener a la gente despierta en las mañanas.',
	'Las hormigas se estiran cuando despiertan en la mañana.',
	'La tierra pesa alrededor de 6,588,000,000,000,000,000,000,000 toneladas.',
	'La orina del gato brilla bajo la luz negra (ultravioleta).',
	'Los toros son daltonicos',
	'Los buhos son las únicas aves que pueden ver el color azul.',
	'Las mujeres parpadean casi el doble que los hombres.',
	'En Estados Unidos los policías comen donas, en México comen tacos.',
	'En el mes de Febrero en el año de 1865 fue el único mes en la historia que no hubo luna llena.',
	'Hay una ciudad llamada Roma en cada continente.',
	'Una cucaracha puede vivir varias semanas sin cabeza.',
	'El coral está hecho de esqueletos de pequeños animales.',
	'La letra Q es la unica del alfabeto que no aparece en ninguno de los nombres de los estados de Estados Unidos.',
	'En Tokio venden peluquines para perros',
	'El transatlantico Titanic tenia cuatro torres de chimenea y solamente tres estaban en operacion, pero como era buena suerte tener cuatro, construyeron una para lucir.',
	'Uno de cada 4 americanos han aparecido en television',
	'La jirafa puede limpiarse los oidos con su lengua de 21 pulgadas de largo.',
	'El cheetah (el guepardo) es el unico felino en el mundo que no puede retractar sus garras.',
	'La letra "J" no aparece en ninguna parte en la tabla periodica de los elementos.',
	'Algunas especies de lombrices son capaces de comerse solas si no encuntran comida.',
	'Un estornudo sale disparado fuera de la Boca a una velocidad mayor a 100 millas por hora.',
	'Un adulto trabajador suda hasta 4 galones por dia. La mayoria de este sudor se evapora antes de que la persona se de cuenta que esta ahi.',
	'Si se mastica una goma de mascar mientras se parte cebolla puede prevenir que te irrite los ojos.',
	'Hay 1,929,770,160,028,800 diferentes combinaciones de color posibles en un cubo de Rubik.',
	'Asi como los perros orinan para marcar su territorio, los gallos cantan en las mañanas para delimitar el suyo. Lo hacen en las mañanas porque a esa hora las aves estan mas activas.',
	'El Rey de Espadas es el unico rey sin bigote.',
	'La navaja dorada encontrada en la tumba del rey Tutankhamen estaba lo suficientemente afilada como para ser usada.',
	'Una persona tipica tiene mas de 1,460 sueños al año.',
	'Pluton, el simbolo astrologico de la muerte, estaba directamente sobre Dallas, Tejas cuando John F. Kennedy nacio.',
	'Las costillas humanas se mueven alrededor de 5 millones de veces al año, o sea, cada vez que respiramos',
	'John Dillinger en 1934 se escapó de una prisión en Indiana, Estados Unidos, amenazando al guardia con una pistola de madera para que abriera la puerta de su celda y lo llevara a la oficina del alcalde de la prisión donde pudo tomar armas de verdad.',
	'Existen mas flamingos de plastico en los Estados Unidos que flamingos de verdad.',
	'Los hombres son 6 veces mas suceptibles de ser golpeados por un rayo que las mujeres.',
	'El oso polar tiene la piel negra bajo su pelambre blanco.',
	'Se estima que 6 millones de personas muertas se encuentran en las Catacumbas de Paris.',
	'Al nacer tenemos 300 huesos, pero de adulto solo tenemos 206.',
	'El champagne fue inventado por un monje del siglo 18 llamado Dom Perignon.',
	'Existen alrededor de 8,000 especies de manzanas',
	'La distancia entre los ojos de un cocodrilo, en pulgadas, es directamente proporcional a todo su largo en pies.',
	'El nombre América, no se puso en honor al cartógrafo Américo Vespuccio sino al parecer vendría del nombre de una tribu de indios del caribe llamados Amaracas.',
	'Mas gente usa cepillos de dientes azules que de color rojo.',
	'Los delfines duermen con un ojo abierto.',
	'En 1694 los jueces se vistieron de negro para llorar la muerte de la reina Maria II y han permanecido asi desde entonces.',
	'El elefante es el unico mamifero que no puede saltar.',
	'En el año 732 despues de Cristo, el Papa Gregorio III prohibio que se comiera la carne de caballo porque era considerado algo malefico ya que antes se acostumbraba sacrificarlo en ceremonias religiosas paganas que incluian beber su sangre y comer su carne',
	'Una persona tipica rie aproximadamente 15 veces diarias.',
	'John Wilkes Booth le disparo a Lincoln en un teatro y fue hallado en un almacen. Lee Harvey Oswald le disparo a Kennedy desde un almacen y fue encontrado en un teatro.',
	'Una arácnido llamado la araña violín es conocido por su picadura que hace que la piel alrededor de la herida se gangrene o se pudra',
	'Las huellas de las narices se utilizan para identificar perros, asi como las huellas dactilares se utilizan para identificar humanos.',
	'Los molinos de viento siempre giran al contrario de las manecillas del reloj, excepto en Irlanda',
	'La pieza mas antigua de goma de mascar tiene mas de 9,000 años.',
	'Si se pone una ciruela pasa en vaso con champagne espumoso, flotara y se hundirá continuamente.',
	'Sherlock Holmes jamás pronunció la frase "Elemental mi querdio Watson", es más, en ningún libro sobre Holmes aparece un ayudante llamado Watson.(*) El dato sobre que en ningun libro sobre Holmes aparezca ningun ayudante llamado Watson "es totalmente falso',
	'Hay 2,598,960 combinaciones posibles de 5 cartas en un mazo de 52 cartas.',
	'El grasnido del pato no causa eco',
	'El billonesimo dígito de ¶ (pi) es 9.',
	'La posicion de los ojos de un burro le permite verse las cuatro patas al mismo tiempo',
	'El microphatógrafo inventado a principios de 1920 era una máquina creada para enviar secretos durante temporadas de guerra. Su extraordinaria tecnología permitía la inscripción de más de 4,000 palabras en una superficia no más grande que un grano de arroz',
	'Cada vez que lames una estampilla postal, consumes un decimo de una caloria',
	'El pan tipo dona fue inventado en 1847 por Hanson Gregory, un capitan de barco que ni siquiera era cocinero.',
	'El estado de Florida en Estados Unidos es mas grande que el pais de Inglaterrra.',
	'Reciclar un jarra de vidrio ahorra suficiente energia como para ver la television durante 3 horas.',
	'Es posible guiar a una vaca hacia arriba de unos escalones, pero no es posible hacerlo hacia abajo porque las rodillas de las vacas no pueden doblarse de una manera apropiada para caminar cuesta abajo.',
	'Los blanqueadores de ropa que no usan cloro en su fórmula, utilizan "blanqueadores ópticos" que reflejan la luz azul, y ésta, al combinarse con l10a decoloración amarilla en una tela, produce luz blanca que hace que la ropa aparente ser más blanca.',
	'Las células que componen las astas de los alces son las células animales mas rapidas de la naturaleza.',
	'La estrella de mar es uno de los unicos animales que pueden voltear hacia afuera su estomago.',
	'Shirley Temple siempre tenia 56 rizos en su cabello',
	'El pinguino es la única ave que puede nadar pero no puede volar.',
	'Las galletas de la fortuna fueron inventadas en america por Charles Jung en 1918.',
	'El vuelo mas largo que ha hecho una gallina es de 13 segundos.',
	'Los ojos de las abejas tienen un cierto tipo de pelo.',
	'Tomar agua despues de comer reduce el acido en la Boca por un 61 porciento.',
	'Cuando una persona llega a los 70 años de edad, su corazón habrá latido al menos unas 2,800 millones de veces.',
	'Cada 45 segundos se incendia una casa en Estados Unidos (pobre casa!)',
	'En el río Amazonas existe un diminuto, casi invisible pez llamado candirú açu que puede forzar su camino por la uretra humana y causar destrucción fisiológica una vez que abre sus espinas y es casi imposible de extraer sin una intervención quirúrgica.',
	'Antes era contra la ley tener un perro de mascota en una ciudad de Islandia.',
	'Una cuarta parte de los huesos del cuerpo humano se encuentran en los pies.',
	'Baby Ruth se ponia una col debajo de su gorra para mantenerse fresco y se la cambiaba cada dos entradas durante los partidos.',
	'Los murcielagos siempre dan vuelta a la izquierda cuando salen de una cueva.',
	'El 90 por ciento de un iceberg flotante está bajo el agua.',
	'Se necesitan 14 minutos para hacer un huevo duro de avestruz.',
	'La piel del tigre es rallada, no solo su pelambre',
	'Naurú, una pequeña isla en el Pacífico Central, es un país que durante el siglo 19 basaba su economía totalmente en el "guano", que es el excremento de las aves y murciélagos y es rica en fosfato. Se utiliza como fertilizante.',
	'Un tempano de hielo polar comun y corriente pesa alrededor de 20,000,000 de toneladas.',
	'A la explosión de una estrella se le llama Supernova y se estima que puede generar una energía de ,000,000,000,000,000,000,000,000,000,000,000,000,0 00,000,000,000 ergs. Por comparar, la primera bomba atómica produjo 1,000,000,000,000,000,000,000 ergs de ',
	'Al pronunciar una sílaba, nosotros producimos aproximadamente 200 ergs de energía.',
	'El reloj atómico de Laboratorio de Investigaciones de la Naval en Washington, D.C. en Estados Unidos se atrasa 1 segundo cada 1.7 millones de años.',
	'Cuando Abraham Lincoln fue asesinado estaba viendo una comedia teatral llamada "Mi Primo Americano" por Tom Taylor.',
	'Se les comenzo a poner herraduras a los caballos en la epoca del Imperio Romano cuando estos comenzaron a pavimentar sus calles.',
	'El corazon del erizo late un promedio de 300 veces por minuto.',
	'Los dientes humanos son casi tan duros como piedras',
	'Es contra la ley eructar o estornudar en cierta iglesia en Omaha, Nebrasca en Estados Unidos.',
	'Desde el año de 1600, se han estinguido 109 especies y subespecies de aves.',
	'Las uñas de los dedos de las manos crecen casi cuatro veces mas rapido que las uñas de los dedos de los pies.',
	'En 1890, en Europa, en apoyo a los trabajadores por su demanda por una jornada de trabajo de ocho horas, se comenzó a observar el 1ro de Mayo como el día del trabajo para honrar a los trabajadores internacionalmente.  Los astrónomos creyeron en un tiempo ',
	'Hace mas de 3,000 años, la mayoria de los egipcios morian a la edad aproximada de 30 años.',
	'Cuando el tomate fue recién llevado al Viejo Mundo desde el Nuevo Mundo, los ingleses temían comerlo pues pensaban que era venenoso.',
	'El botulinus, un veneno tan letal que una sola cucharada pequeña puede arrasar con una ciudad completa, se utiliza en diminutas cantidades y es llamada Botox, una toxina sintentizada de botulinus, para desaparecer las arrugas y "patas de gallo" faciales, ',
	'Otros relojeros siguieron ese mismo sistema para no apenar al rey. Ahora es la manera tradicional de hacer relojes.',
	'Todas las gondolas en Venecia, Italia, deben ser pintadas de color negro, a menos que pertenezcan a un alto oficial.',
	'La India dió el derecho de votar a los eunucos en 1994.',
	'La forma tradicional correcta de escribir el numero "4" en numeros romanos es "IV", pero la manera de mostrarlo en una caratula de reloj es "IIII". La leyenda dice que el reloj fue hecho para un rey britanico que cuando lo vio, corrigio (equivocadamente) ',
	'Según nuestras fuentes, al viajar por autopista de la ciudad de México, D.F. hasta Acapulco, Guerrero, te gastas en cuotas por utilizar la carretera de ida y vuelta aproximadamente $160 Dólares.',
	'El plasma es para los médicos la parte fluida y separada de la materia suspendida de de la sangre, los humores linfáticos o la leche. Para los físicos es una colección de electrones cargados negativamente y iones cargados positivamente, existiendo en igua',
	'Existen 4 formas de matrimonio, la monogamia que es una esposa y un esposo, la poligamia que es un esposo y varias esposas. Además está el matrimonio de una esposa y varios esposos que no recuerdo como se llama y el matrimonio en grupo en el que intervien',
	'Jack Broughton de la Gran Bretaña inventó el guante de boxeo. Fue campión de boxeo a mano limpia y además escribio el primer set de reglas de boxeo.',
	'El himno nacional de Holanda (Het Wilhelmus) es el himno nacional mas antiguo del mundo. La musica aparecio en 1572 y la letra en 1590.',
	'La mantis religiosa o campamocha es el unico insecto que puede voltear su cabeza.',
	'El famoso retrato del bebé de la portada de los frascos de la comida para niños marca Gerber es de una bebita llamada Ann Turner y fué dibujada por Dorothy Hope Smith en 1928.',
	'Mas de 1000 aves mueren anualmente por estrellarse contra ventanas.',
	'La rana Kermit (la rana Rene) de Plaza Sesamo y el Show de los Muppets, es zurda.',
	'Bette Nesmith Graham usaba pintura blanca para pared para cubrir sus errores al escribir para no perder su empleo de oficinista. Bette desarrollo una mejor fórmula antes de patentar su invento que llamó "Liquid Paper".',
	'Un topo puede cavar un tunel de 300 pies de largo en solo una noche.',
	'Un hipopotamo puede abrir su Boca lo suficientemente grande como para que quepa un niño de 4 pies de alto dentro de ella.',
	'El primer hombre ejecutado por electrocución en la silla eléctrica, fue William Kemmler, quien utilizó un hacha para asesinar. Esto fue el 6 de Agosto de 1890, en la prisión del estado de Auburn, en Nueva York. Harold P. Brown habia concievido la idea de',
	'El corazon humano tipico late mas de 100,000 veces en un dia.',
	'El pH de la leche de vaca es de 6.',
	'El trecho de Mairanas es la parte mas profunda del oceano (35,839 pies) y le tomaria a un peso de un kilogramo una hora caer hasta el fondo.',
	'Hay mas peliculas de Holliwood que se han hecho sobre Box que de cualquier otro deporte.',
	'Las donas causan que la persona se vuelva más activa, por sus altos contenidos en azúcares y harina.',
	'El mamifero mas pequeño del mundo es el murcielago abejorro de Tailandia que pesa menos que una moneda de un centavo americano (un penny)',
	'Los egiptos antiguos dormían en almohadas hechas de piedra',
	'Un colibri pesa menos que un penny.',
	'En las primeras maquinas de escribir, el alfabeto tenia un diseño recto de la A a la Z de izquierda a derecha y de arriba hacia abajo, hasta que Christopher Sholes redistribuyo las teclas que mas se utilizan lejos unas de otras para evitar que se trabaran',
	'En la tierra, se producen alrededor de 6,000 rayos atmosfericos cada minuto.',
	'La letra o texto del himno nacional japones data del siglo IX pero la musica fue compuesta en 1880.',
	'Los tacos causan pesadez y sueño al digerirse por la carne roja.',
	'Cuando la luz pasa a travez de la atmosfera terrestre, los colores son desviados y dispersados en muchas direcciones por las moleculas atmosfericas. Los colores azul y morado son los que mas se desvian haciendo que se dispersen por todo el cielo, por eso',
	'A partir del siglo VIII d.C. y durante casi 5 siglos, los moros gobernaron grandes territorios de la europa meridional incluyendo España, en donde los españoles de tez clara y moros de tez oscura se mesclaron dando origen a españoles de tez morena. No obs',
	'Parpadeamos mas de 10,000,000 de veces en un año.',
	'El nombre mas comun en Italia es Mario Rossi.',
	'En cada caja de Cracker Jack hay 9 nueces por cada onza, menos que en la caja original de 1893.',
	'Un inventor de Massachusetts en Estados Unidos, llamado Earl D. Tupper inventó en 1942 el Tupperware, que son los recipientes de plástico durable para guardar alimentos. El nuevo plástico que utilizó para sus experimentos era el polietileno. Tupper trabaj',
	'Shannon Hoon, el ahora muerto cantante del grupo Blind Melon era el cantante de respaldo para el grupo Guns N\'Roses en el album titulado "Use Your Illusion 1".',
	'El numero 142857 es un numero ciclico. Cuando se multiplica por cualquier numero del 1 al 6, los digitos del producto siempre seran los mismo que 142857 y hasta en la misma secuencia, lo unico que cambia el numero por donde comienza. Por ejemplo: 142857 x',
	'Los huesos femures son mas duros que el concreto',
	'Si tu tienes una enfermedad del corazón que se congénita, corres el riesgo de que si te pones aretes en partes de tu cuerpo puedas desarrollar una infección valvular de corazón. Asegúrate de pedir antibióticos preventivos. Información tomada de la revista',
	'El trigo es, por mucho, la planta más cultivada en el mundo y de hecho es la base de la civilización occidental, además de que ha sido cultivada por más de 7,000 años en todos los continentes a excepción de la Antártica.',
	'Los nativos de Centro y Sudamérica utilizan el veneno producido por una rana de la especie de dendrobatidas para sus dardos venenosos.',
	'El 20 porciento del metano que hay en la atmósfera es debido a las emisiones de gases producidos por insectos y animales domésticos (como vacas y cucarachas) y éste metano es culpable de una buena parte del efecto invernadero que ocasiona el calentamiento',
	'Al ave Kea que habita en Nueva Zelandia y mide dos pies de largo, le gusta comerse las tiras de hule que protegen alrededor de las ventanas de los automóviles.',
	'Originalmente el sastre Levi Strauss, de San Francisco California en Estados Unidos, hacía sus jeans de lona, pero a principios de 1860, comenzó a utilizar una tela más suave que importaba de Nîmes, Francia. Conocida en Francia como serge de Nîmes, el mat',
	'George Bunting, un farmacéutico de Baltimore, Estados Unidos, creó una crema para la piel que llamó el "Remedio contra Quemaduras del Dr. Bunting". Buscó en vano un mejor nombre hasta que un día un cliente entro a su farmacia y le dijo en inglés: "Your su',
	'Durante toda la vida, una persona come alrededor de 60,000 libras de comida, que es equivalente al peso de 6 elefantes.',
	'Se producen mas de 50,000 temblores terrestres en todo el mundo cada año.',
	'Margarita Sames dice que fue la inventora de las "margaritas", una mezcla de un buen tequila, Cointerau, hielo y jugo de lima fresco. La sal es opcional. Esto fue en 1948.',
	'En el siglo IX el Papa ordeno que colocaran un gallo en los campanarios de las iglesias para simbolizar el hecho de que San Pedro negara tres veces a Jesus antes del canto del gallo segun se nos dice en el Evangelio de San Marcos. Como los campanarios de',
	'El premio de los Cracker Jack fue incluido en 1913.',
	'Las tres letras de la marca de calzoncillos para hombres BVD son las iniciales de los tres fundadores de la compañía: Bradley, Voorhees y Day.',
	'Un pino de boliche requiere solo una inclinacion de 7.5 grados para caer.',
	'El jabón de barra marca Ivory flota en el agua debido a un error de producción en 1878 cuando Harley Procter y su primo James Gamble decidieron crear para su compañía un jabón blanco que compitiera con los populares jabones de sus competidores. El product',
	'Algunas especies de insectos pueden volar confortablemente a alturas de entre 2,000 y 4,000 pies.',
	'Una bola de base ball oficial pesa entre 5 y 5.25 onzas.',
	'El camello original de los cigarros Camel era un dromedario árabe llamado "Old Joe" que aparecía en el circo Barnum & Bailey a principios de siglo. En aquel tiempo la compañía tabaquera R.J. Reynolds estaba buscando un nombre exótico y un concepto para li',
	'Las crias de las aves petirojos comen 14 pies de lombrices cada dia.',
	'Una moneda de 25 centavos americanos tienen 119 surcos en su orilla. Una moneda de 10 centavos tiene un surco menos.',
	'Antes se creia que era mala suerte vestir al recien nacido sin antes pesarlo.',
	'Fue contra la ley cerrar de golpe la puerta de los automoviles en una ciudad en Suiza.',
	'El icono de "save" o "guardar" en Microsoft Word aparece como un floppy disk, con la lamina de proteccion de la cinta al lado contrario.',
	'A propósito del dato anterior, el 8 de Julio de 1889, John L. Sullivan le ganó por knock out a Jake Kilrain en el round número 75 del campeonato de pesos pesados en Estados Unidos en Richburg, Mississippi. Esta pelea fue la última en la que no se utilizar',
	'El 1920 editor de un periódico en Elkhart en el estado de Indiana en Estados Unidos le daba a sus colaboradores una prescripción de aspirina con bicarbonato de sodio para no contagiarse de influenza durante una epidemia. Hub Beardsley, presidente de los l',
	'Los laboratiorios Searle fueron los responsables de darle al mundo el aspartame ahora conocido como "Nutrasweet", un derivado aminoácido varios cientos de veces más dulce que el azúcar. Entre otros ingredientes, el Nutrasweet contiene metanol, una substan',
	'Los ojos de los animales nocturnos pueden ver bien de noche debido a un compuesto blanco en la retina llamado guanina, sustancia que proporciona una superficie reflectora que hace que la luz rebote hacia enfrente, dandole a los ojos del animal una segunda',
	'La compañía petrolera Shell antiguamente era una tienda de novedades en Londres, llamada The Shell Shop. A mediados de 1800, el dueño, Marcus Samuel, tuvo mucho éxito vendiendo cajas de conchas de mar. Tambien el importar conchas le trajo dinero y su nego',
	'Antes de 1890 se vendian lapices de varios colores hasta que ese año la compañia L&C Hardmuth de Austria introdujo un nuevo lapiz para dibujo de gran calidad que tenia varios grados de dureza y cuyo exterior estaba pintado de color amarillo.. El lapiz tuv',
	'Según la edición de Agosto de 1999 de la revista Play Boy versión estadounidense, una familia promedio en Estados Unidos gasta aproximadamente $400 dólares al año en tarifas telefónicas y en contraste, una familia promedio en México, gasta algo más de $1,',
	'En la ciudad de Mexicali, en el estado de Baja California en México, un recibo de tarifa eléctrica del mes de Agosto en 1999 para un negocio promedio (como el mío, con 5 empleados), viene siendo de aproximadamente $1,000 Dólares más o menos y puede subir ',
	'Un hoyo de golf tiene 4.25 pulgadas de diámetro y al menos 4 pulgadas de profundo.',
	'La madre de MElanie Griffith es la actriz Tippi Hendren, mejor cononcida por su actuacion principal en la pelicula "The Birds" de Alfred Hitchcock.'
];

module.exports = commands;